version: '2'
services:
  nginx:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  postgres:
    container_name: postgres
    privileged: true
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ~/local_docker_volumes/postgresql/data:/var/lib/postgresql/data
  mysql:
    container_name: mysql
    privileged: true
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - ~/local_docker_volumes/mysql:/var/lib/mysql
  php:
    container_name: php
    build: php
    volumes:
      - ~/src/github.com/fusic/:/var/www/html
    environment:
      - VIRTUAL_HOST=php.seike460.com
  php5:
    container_name: php5
    build: php5
    volumes:
      - ~/src/github.com/fusic:/var/www/html
    environment:
      - VIRTUAL_HOST=php5.seike460.com
