version: '3'
services:
  postgres:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - 【localVolumesPath】:/var/lib/postgresql/data
  phoenix:
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - 【YourVolumes】:/app
    environment:
      - VIRTUAL_HOST=【connectDomain】
