# data-box
data-box:
  image: busybox
  container_name: data-box
# postgresql
postgresql:
  image: postgres
  container_name: postgres-db
  volumes_from:
    - data-box
# php
php:
  build: php
  container_name: php
  links:
    - postgresql:postgresql
  volumes_from:
    - data-box
