# mysql
db:
  environment:
    MYSQL_ROOT_PASSWORD: password
  ports:
    - "3306:3306"
  volumes:
    - ~/var/docker_volumes/mysql_data/:/var/lib/mysql
# django 
web:
  ports:
    - "80:80"
  volumes:
    - ~/var/code/app/:/usr/src/app/
  dns: 8.8.8.8
